### ISSUE TITLE
List of Submission Batches for VCEP Variant Historical Report

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/clinvar-reports#15]
**Request:** Add the distinction to the VCEP Variant Historical Report of whether EP assertions were made as part of the pilot process or afterwards

**Deliverable:** A list of submission batches 

VCEP Curated Variants Calculations April 2022:
https://docs.google.com/spreadsheets/d/1u1Bitj4ClcbOGbSa5pM_VeN8ikZiQfbOwpVfqUXonUw/edit#gid=0

**Comment by larrybabb** [comment]
Final version here (July 2022)
https://docs.google.com/spreadsheets/d/1narS_N7kmkTl8OM1B7JRZqpZtTzf4QPjCthKIMz6hsw/edit
