### ISSUE TITLE
Breakdown of Types of Conflicts for VCEP Variant Historical Report

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/clinvar-reports#16]
**Request:** Add a breakdown of what kind of conflict resolutions were made after EP assertions. This requires details about what types of classifications were submitted that contribute to a VCV's "Conflicting" status

**Deliverable:** A breakdown of the classifications contributing to the overall conflicting status

VCEP Curated Variants Calculations April 2022:
https://docs.google.com/spreadsheets/d/1u1Bitj4ClcbOGbSa5pM_VeN8ikZiQfbOwpVfqUXonUw/edit#gid=0

**Comment by larrybabb** [comment]
Final version here (July 2022)
https://docs.google.com/spreadsheets/d/1narS_N7kmkTl8OM1B7JRZqpZtTzf4QPjCthKIMz6hsw/edit
Turned over to SHarrison in slack.
