### ISSUE TITLE
ClinGen VCEP - ClinVar vs ERepo submissions

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-reports#18]
Hi Larry, I would like to take an updated look at the VCEP submissions in ClinVar vs ERepo. Here is the updated ERepo file https://docs.google.com/spreadsheets/d/1IDUk-2DUf4VMiH66WM86wtbXwN2K_9jP5z6-Y4TwPfc/edit?usp=sharing - just want to check if there has been improvement since I reached out to the VCEPs last month. 

Just let me know if you need any additional information.

**Comment by dazzariti** [comment]
@larrybabb I updated the data in this sheet with data I downloaded today from ERepo - if you'd like me to add it to another file or ticket just let me know. I also attached the tab delimited file here in case it's useful
[erepo.tabbed (3).txt](https://github.com/clingen-data-model/clinvar-reports/files/8874178/erepo.tabbed.3.txt)
.

**Comment by larrybabb** [comment]
I added this to the new version of the ClinGen VCEP report I've been trying to get handed over to Steven. You can see the cleaned up info for data you provided in the "Erepo Variant Cleanup 220622" tab of [this new google sheet](https://docs.google.com/spreadsheets/d/1BCDw9sSFflGQNySt4UfmWJrn7RdCklBt6E6V3ynDs6o/edit#gid=1430811978) I'm prepping. BTW - that cleaned up data is then applied to the main VCEP Variants tab that will be used to produce the results. There are definitely a bunch of new submissions included and some issues were resolved, but as you saw in [my notes on slack last Monday](https://the-tgg.slack.com/archives/C01HY5FPJPJ/p1655737930095249) there are still some concerns with how the VCI/ERepo/CAR are syncing with ClinVar which seems to be causing blanks in some of the fields (variant title, clinvar id, etc..).

**Comment by larrybabb** [comment]
@dazzariti please let me know if you feel this specific task is complete or not. if it is please feel free to close it.

**Comment by dazzariti** [comment]
Thank Larry! I do think this is complete and closing the ticket. Much appreciated!
