### ISSUE TITLE
Update Permissions on Expert Panel ClinVar Report

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-reports#23]
Danielle is not able to "Get Release!" due to permission issue

![Screen Shot 2022-11-04 at 5 05 20 PM](https://user-images.githubusercontent.com/10732982/200074661-689bc8f3-9adc-42d9-9f8b-68782a2678f3.png)

**Comment by larrybabb** [comment]
@dazzariti please close this if it is fixed. I think we took care of this.
