### ISSUE TITLE
Data Not Refreshing in Outlier Discrepant ClinVar Variations

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-reports#24]
Users are unable to refresh the data and generate updated statistic tables in the Outlier Discrepant ClinVar Variations. Charts show "No Data"

<img width="1046" alt="Screen Shot 2022-12-20 at 1 32 09 PM" src="https://user-images.githubusercontent.com/10732982/208740391-9e6b67c0-9962-4417-afa6-c148550d52a5.png">

https://docs.google.com/spreadsheets/d/11XbauM053vdOWhQzCFiOG0mcZ2MLG97g3ElEGueQaiQ/edit?usp=sharing

**Comment by larrybabb** [comment]
I fixed the underlying view and refreshed this to the latest clinvar release. Should be okay for now. please review and close if you feel it's fixed.

**Comment by dazzariti** [comment]
Looks good!
