### ISSUE TITLE
Outlier Discrepant ClinVar Variations Sheet - Missing Data

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-reports#25]
Julie is using the Outlier Discrepant ClinVar Variations report for CvC curation - data is now missing from the ClinSig report tab

https://docs.google.com/spreadsheets/d/11XbauM053vdOWhQzCFiOG0mcZ2MLG97g3ElEGueQaiQ/edit?usp=sharing

Reported initially on Slack Jan 3

@larrybabb We discussed at our CvC check in today, Heidi said when you're back this should be your highest priority

**Comment by larrybabb** [comment]
So sorry for the delay at getting this back up and running. I must have accidentally changed the release date value on the Home page and this should only be changed to reflect the latest release once I update the dataset it uses. It should be fixed now, and I added a permission to not edit that value going forward.

**Comment by dazzariti** [comment]
Julie confirmed this is resolved, thank you!
