### ISSUE TITLE
Add Latest Version of EP Gene List file to Google Cloud Bucket

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-reports#7]
Terry, attached is the updated EP Gene List which I tried to upload to https://console.cloud.google.com/storage/browser/clinvar-reports/EP_GeneList_Contacts?orgonly=true&project=clingen-dev&supportedpurview=organizationId&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false and received an Error![Screen Shot 2021-08-04 at 5.29.38 PM.png](https://images.zenhubusercontent.com/60462f15048353c9abbb5b8c/de912fae-0224-426c-8b53-3d127db285e0)

Update file can be found here https://docs.google.com/spreadsheets/d/1M98y9H5CfD2Mmlc3O0Hvwa-buUBcHyz3Nr8UUt5-LPI/edit?usp=sharing

Just let me know if you need any additional information.

**Comment by toneillbroad** [comment]
It appears Danielle has a permissions issue moving the file to the cloud bucket I will look into.

Steps taken:
-  successfully ran the EP Reports locally with the new file.
- Moved the file to the bucket.
- Created a new clinvar reports container (the one that runs Fridays) and pushed the image.
- Tested the image locally but with files to gs://clinvar-reports.

**Comment by dazzariti** [comment]
@toneillbroad Here is the updated EP Contact list [https://app.zenhub.com/files/176358492/2e80ba4c-18fa-4e14-b246-0f58b128ccdd/download](https://app.zenhub.com/files/176358492/2e80ba4c-18fa-4e14-b246-0f58b128ccdd/download)
